server:
  port: 8761
---
#单机实现
spring:
  config:
    activate:
      on-profile: standalone
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
#多节点1
spring:
  config:
    activate:
      on-profile: peer1
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: https://peer1/eureka/,http://peer2/eureka/,http://peer3/eureka/
---
#多节点2
spring:
  config:
    activate:
      on-profile: peer2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: https://peer1/eureka/,http://peer2/eureka/,http://peer3/eureka/
---
#多节点3
spring:
  config:
    activate:
      on-profile: peer3
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: https://peer1/eureka/,http://peer2/eureka/,http://peer3/eureka/
